apiVersion: v1
kind: ConfigMap
metadata:
  name: kse-labs-ca
  namespace: applications
data:
  internal-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDJzCCAg+gAwIBAgIUFOsG7d/N2q5YTUpFA48QhRxemhwwDQYJKoZIhvcNAQEL
    BQAwGzEZMBcGA1UEAxMQa3NlLWxhYnMgUm9vdCBDQTAeFw0yNjA2MTAyMDI4Mjha
    Fw0zNjA2MDcyMDI4NThaMBsxGTAXBgNVBAMTEGtzZS1sYWJzIFJvb3QgQ0EwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/nJHZE9qtu+55KhVdo3aXLhef
    ju2j+qk8huAtQtSZLFrnPBtdJfTL1g4RN4Lni3gdVnJDWZkX/rkCY2gKFGSRMMSm
    PdPyafPmj+1QBXoCfuU4Y1LO0NgQ6/JtOlJSxu9kAoSuVCLctRBE9JXUQKVuDVU0
    Ql89K7bhTDseZIccInoQjGO8NaQbIfoKzkXgd/ikKcZxnPZyvmGUZ03RwUuv+GcY
    cgbV38iNJNN1O1giw09J6lHpgz2P4BI5BWCpY4Gxr97+c/9ycflsDXTzZun2MexP
    16l0ZQRzWD3aXuwMbjv/1hQ5FGElgyRyDZTBlsrFkZTLBmtzDNQfHxd0PC0xAgMB
    AAGjYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBQtjFJIa7vcBlOq5B5F9UudlwB7/TAfBgNVHSMEGDAWgBQtjFJIa7vcBlOq5B5F
    9UudlwB7/TANBgkqhkiG9w0BAQsFAAOCAQEALXGXswueFS1ykF4lU2JIJai2D4NI
    5qIiWWsGKteCwwf0rNGitfK8BhS4mdSRKVXp+WTPrtlDx7MGu3uNlD1q5MOjtxvX
    k06cS0w82/oE9GR9erhrlfim4LZF1//elBo+wKjzZR2YCtPgqmogQ/jk24YdBX48
    ad8JKYyJ5Rk0t4OHUsmeXHbBw8Po3vXnpugheBF3w1dYFjz7slsZPlK2IPEhI5xB
    GRrp65Ffg34nnB9KstdYO1V2ez0enztdT6w+AxdYx1Hl5yAU7nsThtfZbTuuKsXo
    hmtFfYjhVu5ynTCmm+3cPF9Ks2aRgP9mqzVswWwr76yqpAypPCwgixZlxA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDrTCCApWgAwIBAgIUMXDmOvOlUGvJZkmLNOKUCZyR8uEwDQYJKoZIhvcNAQEL
    BQAwGzEZMBcGA1UEAxMQa3NlLWxhYnMgUm9vdCBDQTAeFw0yNjA2MTAyMDI4Mjla
    Fw0zMTA2MDkyMDI4NTlaMCMxITAfBgNVBAMTGGtzZS1sYWJzIEludGVybWVkaWF0
    ZSBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOemQJoNgqLAEdoz
    5NFsumYD2JBXGpwwpS74vRW1afN2PtGo0FdsisPVs61MS230PZX7TfxQc3vTFH6E
    iK1YTDAiNjYNBbd2s6u2jLAh7redmm/Csle0oqvkdC9KseAUOqsxIEfDIIWxHps6
    G0G9Itl+Ez+fdlhiretpptJ7x5Bt1jYGO3is8Kv17SsydzyVMz2dxT7DVhHsVgTn
    VznpSFKKXJTnYTLa14y3z3ZwwCXpHrA9FC3ZsG/bATHws17QxrLj8fW895da22Hl
    JahrGU4GM8QjTxht+FS0H+zt9XNMehIrQLRpcAvAjJqCj3H4wstNWgUgslH3J/YL
    UZHStEMCAwEAAaOB4DCB3TAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUcGOpqcCChPxTCutEaaeoeV/6OrowHwYDVR0jBBgwFoAULYxS
    SGu73AZTquQeRfVLnZcAe/0wQQYIKwYBBQUHAQEENTAzMDEGCCsGAQUFBzAChiVo
    dHRwOi8vdmF1bHQudmF1bHQuc3ZjOjgyMDAvdjEvcGtpL2NhMDcGA1UdHwQwMC4w
    LKAqoCiGJmh0dHA6Ly92YXVsdC52YXVsdC5zdmM6ODIwMC92MS9wa2kvY3JsMA0G
    CSqGSIb3DQEBCwUAA4IBAQAAjXXFzwi0htIXH/e0aicd7lTeERfV51C7f/YjHRxq
    3EyRu9oauvQWFjdL1gLC4ykOobANl0Ws/pOonEAPWq0cx+CPsa/ZxSiVdfbQnshu
    yDfgHt4vEr7KkVva23Vsby064zGeXzyyT7SlN+8T2aDiNY01Udjn3su3uAE1gsU2
    9yNW2el9rgisyLyCXMa7+RkNn3nC97KXbxhoyIoexHRaFY2o9CErfCWPYIFoolsy
    H0eHRn+i8dgj0pxpOvyR8TnGaJmpYKzuQx/33NFKedNcXg8lxIv+34g5TYII0QqE
    IUPkVUQ5NznySTi8Sg+6K95S0skaTh6WqdOpF3PdW2Fc
    -----END CERTIFICATE-----
