apiVersion: v1
kind: ConfigMap
metadata:
  name: kse-labs-ca
  namespace: applications
data:
  internal-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDJzCCAg+gAwIBAgIUFOsG7d/N2q5YTUpFA48QhRxemhwwDQYJKoZIhvcNAQEL
    BQAwGzEZMBcGA1UEAxMQa3NlLWxhYnMgUm9vdCBDQTAeFw0yNjA2MTAyMDI4Mjha
    Fw0zNjA2MDcyMDI4NThaMBsxGTAXBgNVBAMTEGtzZS1sYWJzIFJvb3QgQ0EwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/nJHZE9qtu+55KhVdo3aXLhef
    ju2j+qk8huAtQtSZLFrnPBtdJfTL1g4RN4Lni3gdVnJDWZkX/rkCY2gKFGSRMMSm
    PdPyafPmj+1QBXoCfuU4Y1LO0NgQ6/JtOlJSxu9kAoSuVCLctRBE9JXUQKVuDVU0
    Ql89K7bhTDseZIccInoQjGO8NaQbIfoKzkXgd/ikKcZxnPZyvmGUZ03RwUuv+GcY
    cgbV38iNJNN1O1giw09J6lHpgz2P4BI5BWCpY4Gxr97+c/9ycflsDXTzZun2MexP
    16l0ZQRzWD3aXuwMbjv/1hQ5FGElgyRyDZTBlsrFkZTLBmtzDNQfHxd0PC0xAgMB
    AAGjYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBQtjFJIa7vcBlOq5B5F9UudlwB7/TAfBgNVHSMEGDAWgBQtjFJIa7vcBlOq5B5F
    9UudlwB7/TANBgkqhkiG9w0BAQsFAAOCAQEALXGXswueFS1ykF4lU2JIJai2D4NI
    5qIiWWsGKteCwwf0rNGitfK8BhS4mdSRKVXp+WTPrtlDx7MGu3uNlD1q5MOjtxvX
    k06cS0w82/oE9GR9erhrlfim4LZF1//elBo+wKjzZR2YCtPgqmogQ/jk24YdBX48
    ad8JKYyJ5Rk0t4OHUsmeXHbBw8Po3vXnpugheBF3w1dYFjz7slsZPlK2IPEhI5xB
    GRrp65Ffg34nnB9KstdYO1V2ez0enztdT6w+AxdYx1Hl5yAU7nsThtfZbTuuKsXo
    hmtFfYjhVu5ynTCmm+3cPF9Ks2aRgP9mqzVswWwr76yqpAypPCwgixZlxA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFJzCCAw+gAwIBAgIUZRJdKcl1kUgj7HKAMSV+9YMXfE0wDQYJKoZIhvcNAQEL
    BQAwGzEZMBcGA1UEAwwQa3NlLWxhYnMgUm9vdCBDQTAeFw0yNjA2MTgwODU4Mjda
    Fw0zNjA2MTUwODU4MjdaMBsxGTAXBgNVBAMMEGtzZS1sYWJzIFJvb3QgQ0EwggIi
    MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDAg0GvavKkGQi7EfnhZCiPzNcv
    1simVXjYxc2luRFSAqrDrKRbMrO81fm1LZiQI+yhj/oWmm5Ds8wEAt3lyXSXnf5+
    gA40PVoLx01SqHFW6sf5E1r2FuexlrfwpEUljueKxJbEnmFGG/YOO1NsPshFR8QE
    wwp8EKBOAa8Buy1HOaYd2bDyu2Krf3VqNFj/K6KLhWi5teb3r5fA0FoUabbAo1XN
    n1StV2g+yBJlcJKleUThdBX76aAOiqEZk6lDcShckE/WoJV0RZ3xNfxLyLrYfx2P
    bOYRsfIhL0egtOkq4hUt31usVEUb+3mF5qrsjuJ3EXBrkM3xzAFFG1twcNw38T1Z
    YT05S3gWI1YE6x3Lfvd1u5HaO1llXvUD7G8vye5EcKNEEhMn/I+u86gMqlLN8dFX
    iVJm+8XX5I6PQuru7KZC5AugldyRLuWN3q5m61Q4N3fPUO13ZBFyiM1pbuKx8t8T
    h/Rx9G1oWy6u2dGZbEUoO/62mX5Md+6dfHDAofn+Rcs0VbWvvI45tU/A3aS9oqgQ
    ilXxmR1o3xcpeF2hE3I4facPauIRIj5gbyZZ2dlob0nCkpWJRAE1sONiG3xM3wtw
    z/HxNmzHdb/TpunQsDaZeDw2My+1kk1Mn8HsRuEBqMwNsQyseioUnSpIjhbib1pn
    7WK6Aqu7EBU6nk+PcQIDAQABo2MwYTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB
    /wQEAwIBBjAdBgNVHQ4EFgQUodmfQP0y7UMsNyAGi94OYPVBfkIwHwYDVR0jBBgw
    FoAUodmfQP0y7UMsNyAGi94OYPVBfkIwDQYJKoZIhvcNAQELBQADggIBAI1O2jab
    FBVvzpp9Xf9ycDgHc9IjpLOj0HuZhRoSKPcZZ1Antt/NDzuDz9pmsPurRqzXJ3Qu
    MYJh/Aly6BN5tYl+vUAerfV3TYUpE6GHO5PAtrgpx7v/Z9iC1X6NXw4UcEndUX2s
    lT+hcbFslRidgpREzVLB+D+5IOYByh/d++ZIJAKhzCpmMyN7n/ABq72cyXgAXmKO
    FXZuL+F/tOX/z7mwcOy0QhMv2U6sQE9ntXFQN7+AZ2O5zxfzqIT5gfMEiLGpqIt7
    hc8BvGaj62WSWDhAUKx8aZGlcArKzqBxNdrJFOfb1K+6koSEDl6I6htoelRHOYVq
    flxbNvs6x7QAjt+UwNftY308SWztL1fquPag9/oHYvA+5izAY/agyTOnlk0aAAnd
    dmNOBYpooTPZZqXmu+fVl42P0hy1LLteqhd6QtZRc+avxmZyqIZAAosD0ODTllVg
    5E7ZNthkw5h4UPZIhNTTak8i9fVlxu6C7hYTpI+DIhcMVMAJ0nFo9c6IaQwF/wer
    LHipkBaARboCbYnRIuV02H582iBGvzxoCObfFQ9yILWLdIQUhj1VtJUBD6hUBs33
    yz48Q2dZVbpEqHm9vXWU0gFZu8JTUHuKQOjYweCYfGR+s9V0n1ztBSXowGRp5GJe
    2h3i0cWP58FlYgWxbE4Vv0x3hxBa0vGY0h7O
    -----END CERTIFICATE-----
