apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spa-token-demo-tls
  namespace: applications
spec:
  secretName: spa-token-demo-tls
  commonName: spa-token-demo.192.168.50.10.nip.io
  dnsNames:
    - spa-token-demo.192.168.50.10.nip.io
  duration: 720h
  renewBefore: 240h
  issuerRef:
    name: vault-pki-int
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
